# https://starship.rs/config/
# ~/.config/starship.toml

format = '$character$time$all'

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[➜](bold red)'

[time]
disabled = false
format = '[\[](bold blue)[$time]($style)[\]](bold blue) '
time_format = '%H:%M'

[git_status]
stashed = ''
ahead = '⇡${count}'
behind = '⇣${count}'
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
staged = '[+${count}](green)'
modified = '!${count}'
deleted = '✘${count}'


[kubernetes]
disabled = false


[line_break]
disabled = true
[golang]
disabled = true
[helm]
disabled = true
[java]
disabled = true
[nodejs]
disabled = true
[package]
disabled = true
[python]
disabled = true
[terraform]
disabled = true
